apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-app-pipeline:1.0.0-11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: vignesh2064/devops-cicd-app-pipeline:1.0.0-11
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
